# Site settings
title: PKE
email: rully@pili.or.id
description: "PKE - PUSAT KONSERVASI ELANG KAMOJANG"
baseurl: ''

# Build settings
encoding: utf-8
markdown: kramdown
permalink: pretty
exclude: [old]

# Blog & RSS settings
name: Mayday PAC Blog
url: http://rullyvm.github.io/pke
